# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tlouekar <tlouekar@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/24 09:41:56 by tlouekar          #+#    #+#              #
#    Updated: 2019/12/02 09:09:48 by tlouekar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRCS = ft_atoi.c \
ft_isascii.c \
ft_isprint.c \
ft_isalpha.c \
ft_isdigit.c \
ft_isalnum.c \
ft_bzero.c \
ft_lstdelone.c \
ft_lstadd.c \
ft_lstdel.c \
ft_lstmap.c \
ft_lstiter.c \
ft_memalloc.c \
ft_lstnew.c \
ft_memchr.c \
ft_memdel.c \
ft_memcpy.c \
ft_memcmp.c \
ft_itoa.c \
ft_putendl.c \
ft_putchar.c \
ft_memmove.c \
ft_memset.c \
ft_putstr.c \
ft_putendl_fd.c \
ft_putnbr.c \
ft_putnbr_fd.c \
ft_putstr_fd.c \
ft_memccpy.c \
ft_strclr.c \
ft_strcat.c \
ft_strdel.c \
ft_strcpy.c \
ft_putchar_fd.c \
ft_striter.c \
ft_strcmp.c \
ft_strequ.c \
ft_strchr.c \
ft_strdup.c \
ft_strlen.c \
ft_striteri.c \
ft_strjoin.c \
ft_strmapi.c \
ft_strlcat.c \
ft_strmap.c \
ft_strncat.c \
ft_strncpy.c \
ft_strncmp.c \
ft_strnequ.c \
ft_strrchr.c \
ft_strsub.c \
ft_strnew.c \
ft_toupper.c \
ft_strnstr.c \
ft_tolower.c \
ft_strstr.c \
ft_wordlen.c \
ft_wordcnt.c \
ft_strsplit.c \
ft_strtrim.c \
ft_strcsub.c \

INCS = includes/libft.h

CFLAGS = -Wall -Wextra -Werror

OUTPUT = ft_atoi.o \
ft_isascii.o \
ft_isprint.o \
ft_isalpha.o \
ft_isdigit.o \
ft_isalnum.o \
ft_bzero.o \
ft_lstdelone.o \
ft_lstadd.o \
ft_lstdel.o \
ft_lstmap.o \
ft_lstiter.o \
ft_memalloc.o \
ft_lstnew.o \
ft_memchr.o \
ft_memdel.o \
ft_memcpy.o \
ft_memcmp.o \
ft_itoa.o \
ft_putendl.o \
ft_putchar.o \
ft_memmove.o \
ft_memset.o \
ft_putstr.o \
ft_putendl_fd.o \
ft_putnbr.o \
ft_putnbr_fd.o \
ft_putstr_fd.o \
ft_memccpy.o \
ft_strclr.o \
ft_strcat.o \
ft_strdel.o \
ft_strcpy.o \
ft_putchar_fd.o \
ft_striter.o \
ft_strcmp.o \
ft_strequ.o \
ft_strchr.o \
ft_strdup.o \
ft_strlen.o \
ft_striteri.o \
ft_strjoin.o \
ft_strmapi.o \
ft_strlcat.o \
ft_strmap.o \
ft_strncat.o \
ft_strncpy.o \
ft_strncmp.o \
ft_strnequ.o \
ft_strrchr.o \
ft_strsub.o \
ft_strnew.o \
ft_toupper.o \
ft_strnstr.o \
ft_tolower.o \
ft_strstr.o \
ft_wordlen.o \
ft_wordcnt.o \
ft_strsplit.o \
ft_strtrim.o \
ft_strcsub.o \

EXE = a.out

MAIN = ../main.c

all: $(NAME)

$(NAME):
	gcc $(CFLAGS) -I $(INCS) -c $(SRCS)
	ar rc $(NAME) $(OUTPUT)
	ranlib $(NAME)

norm:
	norminette $(SRCS)

clean:
	/bin/rm -f $(OUTPUT)

exe:
	gcc $(CFLAGS) -o $(EXE) $(MAIN) -I $(INCS) -L. -lft

fclean: clean
	rm -f $(NAME)
	
re: fclean all

fuckall: fclean norm all exe
